return {
  ensure_installed = {
    "gofumpt",
    "goimports",
    "golines",
    "gopls",
    "golangci-lint",
    "lua_ls",
    "rust-analyzer",
    "rustfmt",
    "stylua",
    "pyright",
    "flake8",
    "isort",
    "black",
    "pylint",
    "tsserver",
    "html",
    "cssls",
    "tailwindcss",
    "prettierd",
    "eslint_d",
    "emmet_ls",
    "nil_ls",
    "nixpkgs-fmt",
  },
}
